version: '3.1'

services:
    pycontw-postgresql:
        restart: always
        image: postgres:11.1
        container_name: pycontw-postgresql
        hostname: pycontw-postgresql
        environment:
            POSTGRES_PASSWORD: pwd
            POSTGRES_USER: username
        ports:
            - 5432:5432

networks:
    default:
        external:
            name: pycontw-net
